name: frontend
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  authn:
    path: dart_cli/packages/authn
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  #flutter_secure_storage: ^9.0.0 #uncomment this if you want to use real secure storage
  flutter_spinkit: ^5.2.0
  go_router: ^13.0.0
  graphql_flutter: ^5.1.2
  intl: ^0.17.0
  mobile_scanner: 3.5.5
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logos/findywallet.png
    - assets/logos/findywallet_white.png
    - assets/icons/profile.png
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf
