name: authn
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-65.0.dev

# Add regular dependencies here.
dependencies:
  basic_utils: ^5.5.4
  cbor: ^5.1.2
  cryptography: ^2.7.0
  fixnum: ^1.1.0
  grpc: ^3.2.4
  yaml: ^3.1.2

  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
