name: flutter_ci

on:
  push:
    branches: [ "test-branch" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.x'
        channel: 'beta'
    - run: flutter pub get
      working-directory: frontend
    - run: flutter build apk
      working-directory: frontend
    - run: flutter build appbundle
      working-directory: frontend
    - run: flutter analyze
      working-directory: frontend
    - run: flutter test
      working-directory: frontend

  ios-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.x'
        channel: 'beta'
    - run: flutter pub get
      working-directory: frontend
    - run: flutter build ios --release --no-codesign
      working-directory: frontend
    - run: flutter analyze
      working-directory: frontend
    - run: flutter test
      working-directory: frontend
